routes/web.php
<?php

use App\Http\Controllers\CartController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\ProductCategoryController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\TransactionController;
use App\Http\Controllers\WelcomeController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [WelcomeController::class, 'index']);
Route::post('/chart', [WelcomeController::class, 'chart']);

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::middleware('auth')->group( function () {
    Route::get('product/categoryselect', [ProductController::class, 'categoryselect']);
    Route::resource('product', ProductController::class);

    Route::resource('productcategory', ProductCategoryController::class);
    Route::resource('customer', CustomerController::class);

    Route::resource('cart', CartController::class);
    Route::resource('transaction', TransactionController::class);
});

app/Models/ProductCategory.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class ProductCategory extends Model
{
    use HasFactory, SoftDeletes;

    protected $guarded = [];
}

app/Http/Controllers/ProductCategoryController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ProductCategoryRequest;
use App\Models\ProductCategory;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Yajra\DataTables\Facades\DataTables;

class ProductCategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public $data = [
        'title' => 'Kategori Produk',
    ];

    public function index()
    {
        if (request()->ajax()) {

            $query = ProductCategory::get();


            return  DataTables::of($query)
                ->addIndexColumn()
                ->addColumn('action', function($item){
                    return '
                        <a class="btn btn-primary btn-sm" href="'.route('productcategory.edit', $item->id).'">
                            Edit
                        </a>
                        <a class="btn btn-warning btn-sm" href="'.route('productcategory.show', $item->id).'">
                            Detail
                        </a>
                        <a class="btn btn-danger btn-sm delete" href="#" data-url="'.route('productcategory.destroy', $item->id).'">
                            Delete
                        </a>
                    ';
                })
                ->make();
        }

        return view('productcategory.index', $this->data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('productcategory.create', $this->data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ProductCategoryRequest $request)
    {
        if ($request->validator && $request->validator->fails()) {
            return response()->json([
                'status'    => false,
                'message'   => $request->validator->getMessageBag()->first()
            ], 400);
        }

        DB::beginTransaction();
        $product = ProductCategory::create($request->all());

        if (!$product) {
            DB::rollBack();
            return response()->json([
                'status'    => false,
                'message'   => $product
            ], 400);
        }

        DB::commit();
        return response()->json([
            'status'    => true,
            'results'   => route('productcategory.index')
        ], 200);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $this->data['data'] = ProductCategory::findOrFail($id);

        return view('productcategory.show', $this->data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $this->data['data'] = ProductCategory::findOrFail($id);

        return view('productcategory.edit', $this->data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if ($request->validator && $request->validator->fails()) {
            return response()->json([
                'status'    => false,
                'message'   => $request->validator->getMessageBag()->first()
            ], 400);
        }

        DB::beginTransaction();
        $product = ProductCategory::find($id);
        $product->update($request->all());

        if (!$product) {
            DB::rollBack();
            return response()->json([
                'status'    => false,
                'message'   => $product
            ], 400);
        }

        DB::commit();
        return response()->json([
            'status'    => true,
            'results'   => route('productcategory.index')
        ], 200);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            $product = ProductCategory::find($id);
            $product->delete();
        } catch (\Illuminate\Database\QueryException $e) {
            return response()->json([
                'status'     => false,
                'message'     => 'Error delete data'
            ], 400);
        }
        return response()->json([
            'status'     => true,
            'message' => 'Success delete data'
        ], 200);
    }
}

resources/views/productcategory/create.blade.php
@extends('layouts.app')

@section('stylesheets')
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css" rel="stylesheet" />
<link href="{{asset('component/bootstrap-fileinput/css/fileinput.min.css')}}" rel="stylesheet">
<link href="{{asset('component/bootstrap-fileinput/themes/explorer-fas/theme.min.css')}}" rel="stylesheet">
<style>
    .select2-container--default{
        width: inherit !important;
    }
    .select2-container--default .select2-selection--single {
        background-color: #F3F7FF !important;
        height: 34px !important;
    }
    .select2-container--default .select2-selection--single .select2-selection__placeholder{
        color: #c4c4c4;
    }
    .select2-container{
        width: 100% !important;
    }
    .select2-selection{
        height: 2.7em !important;
        padding-top: 0.3em;
    }
</style>
@endsection

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Tambah {{ $title }}</div>

                <div class="card-body">

                    <form id="form" action="{{ route('productcategory.store') }}" method="POST">
                        @csrf
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label>Nama Kategori <b class="text-danger">*</b></label>
                                <input type="text" name="name" class="form-control" placeholder="Nama Kategori">
                            </div>
                        </div>
                        <div class="float-right">
                            <button type="submit" class="btn btn-success">Simpan</button>
                        </div>
                    </form>
                </div>
                <div class="overlay d-none">
                    <i class="fa fa-2x fa-sync-alt fa-spin"></i>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

@push('scripts')
<script src="{{asset('component/validate/jquery.validate.min.js')}}"></script>
<script src="https://cdn.ckeditor.com/ckeditor5/31.0.0/classic/ckeditor.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"></script>
<script src="{{asset('component/bootstrap-fileinput/js/fileinput.min.js')}}"></script>
<script src="{{asset('component/bootstrap-fileinput/themes/explorer-fas/theme.min.js')}}"></script>
    <script>

        $(document).ready(function(){

            $("#form").validate({
                errorElement: 'div',
                errorClass: 'invalid-feedback',
                focusInvalid: false,
                highlight: function (e) {
                    $(e).closest('.form-group').removeClass('has-success').addClass('was-validated has-error');
                },

                success: function (e) {
                    $(e).closest('.form-group').removeClass('has-error').addClass('has-success');
                    $(e).remove();
                },
                errorPlacement: function (error, element) {
                    if(element.is(':file')) {
                    error.insertAfter(element.parent().parent().parent());
                    }else
                    if(element.parent('.input-group').length) {
                    error.insertAfter(element.parent());
                    }
                    else
                    if (element.attr('type') == 'checkbox') {
                        error.insertAfter(element.parent());
                    }
                    else{
                        error.insertAfter(element);
                    }
                    },
                    submitHandler: function() {
                    $.ajax({
                        url:$('#form').attr('action'),
                        method:'post',
                        data: new FormData($('#form')[0]),
                        processData: false,
                        contentType: false,
                        dataType: 'json',
                        beforeSend:function(){
                          $('.overlay').removeClass('d-none');
                        }
                    }).done(function(response){
                        $('.overlay').addClass('d-none');
                        if(response.status){
                            document.location = response.results;
                        }
                        else{
                        $.gritter.add({
                            title: 'Warning!',
                            text: response.message,
                            class_name: 'gritter-warning',
                            time: 1000,
                        });
                        }
                        return;
                    }).fail(function(response){
                        $('.overlay').addClass('d-none');
                        var response = response.responseJSON;
                        $.gritter.add({
                            title: 'Error!',
                            text: response.message,
                            class_name: 'gritter-error',
                            time: 1000,
                        });
                    })
                }
            });


        });
    </script>
@endpush

resources/views/productcategory/edit.blade.php
@extends('layouts.app')

@section('stylesheets')
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css" rel="stylesheet" />
<link href="{{asset('component/bootstrap-fileinput/css/fileinput.min.css')}}" rel="stylesheet">
<link href="{{asset('component/bootstrap-fileinput/themes/explorer-fas/theme.min.css')}}" rel="stylesheet">
<style>
    .select2-container--default{
        width: inherit !important;
    }
    .select2-container--default .select2-selection--single {
        background-color: #F3F7FF !important;
        height: 34px !important;
    }
    .select2-container--default .select2-selection--single .select2-selection__placeholder{
        color: #c4c4c4;
    }
    .select2-container{
        width: 100% !important;
    }
    .select2-selection{
        height: 2.7em !important;
        padding-top: 0.3em;
    }
</style>
@endsection

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Edit {{ $title }}</div>

                <div class="card-body">

                    <form id="form" action="{{ route('productcategory.update', $data->id) }}" method="POST">
                        @csrf
                        @method('put')
                        <input type="hidden" name="id" class="form-control" value="{{ $data->id }}">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label>Nama Kategori Produk <b class="text-danger">*</b></label>
                                <input type="text" name="name" class="form-control" value="{{ $data->name }}" placeholder="Nama Kategori Produk">
                            </div>
                        </div>
                        <div class="float-right">
                            <button type="submit" class="btn btn-success">Simpan</button>
                        </div>
                    </form>

                </div>
                <div class="overlay d-none">
                    <i class="fa fa-2x fa-sync-alt fa-spin"></i>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@push('scripts')
<script src="{{asset('component/validate/jquery.validate.min.js')}}"></script>
<script src="https://cdn.ckeditor.com/ckeditor5/31.0.0/classic/ckeditor.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"></script>
<script src="{{asset('component/bootstrap-fileinput/js/fileinput.min.js')}}"></script>
<script src="{{asset('component/bootstrap-fileinput/themes/explorer-fas/theme.min.js')}}"></script>
    <script>

        $(document).ready(function(){

            $("#form").validate({
                errorElement: 'div',
                errorClass: 'invalid-feedback',
                focusInvalid: false,
                highlight: function (e) {
                    $(e).closest('.form-group').removeClass('has-success').addClass('was-validated has-error');
                },

                success: function (e) {
                    $(e).closest('.form-group').removeClass('has-error').addClass('has-success');
                    $(e).remove();
                },
                errorPlacement: function (error, element) {
                    if(element.is(':file')) {
                    error.insertAfter(element.parent().parent().parent());
                    }else
                    if(element.parent('.input-group').length) {
                    error.insertAfter(element.parent());
                    }
                    else
                    if (element.attr('type') == 'checkbox') {
                        error.insertAfter(element.parent());
                    }
                    else{
                        error.insertAfter(element);
                    }
                    },
                    submitHandler: function() {
                    $.ajax({
                        url:$('#form').attr('action'),
                        method:'post',
                        data: new FormData($('#form')[0]),
                        processData: false,
                        contentType: false,
                        dataType: 'json',
                        beforeSend:function(){
                        $('.overlay').removeClass('d-none');
                        }
                    }).done(function(response){
                        $('.overlay').addClass('d-none');
                        if(response.status){
                        document.location = response.results;
                        }
                        else{
                        $.gritter.add({
                            title: 'Warning!',
                            text: response.message,
                            class_name: 'gritter-warning',
                            time: 1000,
                        });
                        }
                        return;
                    }).fail(function(response){
                        $('.overlay').addClass('d-none');
                        var response = response.responseJSON;
                        $.gritter.add({
                        title: 'Error!',
                        text: response.message,
                        class_name: 'gritter-error',
                        time: 1000,
                        });
                    })
                }
            });


        });

    </script>
@endpush

resources/views/productcategory/index.blade.php
@extends('layouts.app')

@section('stylesheets')
<link href="{{asset('component/dataTables/css/datatables.min.css')}}" rel="stylesheet">
@endsection

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    {{ $title }}
                    <a href="{{ route('product.create') }}" class="btn btn-success btn-sm float-right">+ Tambah {{ $title }}</a>
                </div>

                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered" id="table-product">
                            <thead>
                                <tr>
                                    <th>No</th>
                                    <th>Nama</th>
                                    <th>Aksi</th>
                                </tr>
                            </thead>
                            <tbody>

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@push('scripts')
    <script src="{{asset('component/dataTables/js/datatables.min.js')}}"></script>
    <script>
        $(document).ready(function(){

            dataTable = $('#table-product').DataTable({
            stateSave:true,
            processing:true,
            serverSide:true,
            info:false,
            lengthChange:true,
            responsive:true,
            ajax: {
                url: '{!! url()->current() !!}',
                type: "GET",
                data: function(data){
                },
            },
            columns: [
                { data: "DT_RowIndex" },
                { data: "name" },
                { data: "action", orderable: false, searchable: false, class: 'text-center' },
            ]
        });

        $(document).on('click','.delete',function(){
            var url = $(this).data('url');
            bootbox.confirm({
                buttons: {
                    confirm: {
                        label: '<i class="fa fa-check"></i>',
                        className: 'btn btn-danger'
                    },
                    cancel: {
                        label: '<i class="fa fa-undo"></i>',
                        className: 'btn btn-secondary'
                    },
                },
                title:'Hapus Produk Kategori?',
                message:'Data yang dihapus tdak bisa dikembalikan',
                callback: function(result) {
                        if(result) {
                            var data = {
                                _token: "{{ csrf_token() }}"
                            };
                            $.ajax({
                                url: url,
                                dataType: 'json',
                                data:data,
                                type:'DELETE',
                                beforeSend:function(){
                                    $('.overlay').removeClass('hidden');
                                }
                            }).done(function(response){
                                if(response.status){
                                    $('.overlay').addClass('hidden');
                                    $.gritter.add({
                                        title: 'Success!',
                                        text: response.message,
                                        class_name: 'gritter-success',
                                        time: 1000,
                                    });
                                    dataTable.ajax.reload( null, false );
                                }
                                else{
                                    $.gritter.add({
                                        title: 'Warning!',
                                        text: response.message,
                                        class_name: 'gritter-warning',
                                        time: 1000,
                                    });
                                }
                            }).fail(function(response){
                                var response = response.responseJSON;
                                $('.overlay').addClass('hidden');
                                $.gritter.add({
                                    title: 'Error!',
                                    text: response.message,
                                    class_name: 'gritter-error',
                                    time: 1000,
                                });
                            })
                        }
                }
            });
        })
    });

    </script>
@endpush

resources/views/productcategory/show.blade.php
@extends('layouts.app')

@section('stylesheets')
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css" rel="stylesheet" />
<link href="{{asset('component/bootstrap-fileinput/css/fileinput.min.css')}}" rel="stylesheet">
<link href="{{asset('component/bootstrap-fileinput/themes/explorer-fas/theme.min.css')}}" rel="stylesheet">
<style>
    .select2-container--default{
        width: inherit !important;
    }
    .select2-container--default .select2-selection--single {
        background-color: #F3F7FF !important;
        height: 34px !important;
    }
    .select2-container--default .select2-selection--single .select2-selection__placeholder{
        color: #c4c4c4;
    }
    .select2-container{
        width: 100% !important;
    }
    .select2-selection{
        height: 2.7em !important;
        padding-top: 0.3em;
    }
</style>
@endsection

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Detail {{ $title }}</div>

                <div class="card-body">

                    <form id="form" action="{{ route('product.update', $data->id) }}" method="POST">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label>Nama Produk Kategori <b class="text-danger">*</b></label>
                                <input type="text" name="nama" class="form-control" value="{{ $data->name }}" placeholder="Nama Produk Kategori" readonly>
                            </div>
                        </div>

                    </form>

                </div>
                <div class="overlay d-none">
                    <i class="fa fa-2x fa-sync-alt fa-spin"></i>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@push('scripts')
<script src="{{asset('component/validate/jquery.validate.min.js')}}"></script>
<script src="https://cdn.ckeditor.com/ckeditor5/31.0.0/classic/ckeditor.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"></script>
<script src="{{asset('component/bootstrap-fileinput/js/fileinput.min.js')}}"></script>
<script src="{{asset('component/bootstrap-fileinput/themes/explorer-fas/theme.min.js')}}"></script>
    <script>

        $(document).ready(function(){

            $("#form").validate({
                errorElement: 'div',
                errorClass: 'invalid-feedback',
                focusInvalid: false,
                highlight: function (e) {
                    $(e).closest('.form-group').removeClass('has-success').addClass('was-validated has-error');
                },

                success: function (e) {
                    $(e).closest('.form-group').removeClass('has-error').addClass('has-success');
                    $(e).remove();
                },
                errorPlacement: function (error, element) {
                    if(element.is(':file')) {
                    error.insertAfter(element.parent().parent().parent());
                    }else
                    if(element.parent('.input-group').length) {
                    error.insertAfter(element.parent());
                    }
                    else
                    if (element.attr('type') == 'checkbox') {
                        error.insertAfter(element.parent());
                    }
                    else{
                        error.insertAfter(element);
                    }
                    },
                    submitHandler: function() {
                    $.ajax({
                        url:$('#form').attr('action'),
                        method:'post',
                        data: new FormData($('#form')[0]),
                        processData: false,
                        contentType: false,
                        dataType: 'json',
                        beforeSend:function(){
                        $('.overlay').removeClass('d-none');
                        }
                    }).done(function(response){
                        $('.overlay').addClass('d-none');
                        if(response.status){
                        document.location = response.results;
                        }
                        else{
                        $.gritter.add({
                            title: 'Warning!',
                            text: response.message,
                            class_name: 'gritter-warning',
                            time: 1000,
                        });
                        }
                        return;
                    }).fail(function(response){
                        $('.overlay').addClass('d-none');
                        var response = response.responseJSON;
                        $.gritter.add({
                        title: 'Error!',
                        text: response.message,
                        class_name: 'gritter-error',
                        time: 1000,
                        });
                    })
                }
            });


        });
    </script>
@endpush