routes/web.php
<?php

use App\Http\Controllers\CartController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\ProductCategoryController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\TransactionController;
use App\Http\Controllers\WelcomeController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [WelcomeController::class, 'index']);
Route::post('/chart', [WelcomeController::class, 'chart']);

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::middleware('auth')->group( function () {
    Route::get('product/categoryselect', [ProductController::class, 'categoryselect']);
    Route::resource('product', ProductController::class);

    Route::resource('productcategory', ProductCategoryController::class);
    Route::resource('customer', CustomerController::class);

    Route::resource('cart', CartController::class);
    Route::resource('transaction', TransactionController::class);
});

app/Http/Controllers/TransactionController.php
<?php

namespace App\Http\Controllers;

use App\Models\Cart;
use App\Models\Product;
use App\Models\Transaction;
use App\Models\TransactionItem;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Yajra\DataTables\Facades\DataTables;
use Illuminate\Support\Str;

class TransactionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public $data = [
        'title' => 'Transaksi',
    ];

    public function index()
    {
        if (request()->ajax()) {


            $data = Transaction::with('user');
            if (Auth::user()->role != 'ADMIN') {
                $data->where('user_id', Auth::user()->id);
            }
            $query = $data->get();

            return  DataTables::of($query)
                ->addIndexColumn()
                ->addColumn('customer', function($item){
                    return $item->user->name;
                })
                ->addColumn('action', function($item){
                    $edit = '';
                    if (Auth::user()->role == 'ADMIN') {
                        $edit = '<a class="btn btn-primary btn-sm" href="'.route('transaction.edit', $item->id).'">
                                    Edit
                                </a>';
                    }
                    return $edit.'
                        <a class="btn btn-warning btn-sm" href="'.route('transaction.show', $item->id).'">
                            Detail
                        </a>
                    ';
                })
                ->editColumn('total_price', function($item){
                    return 'Rp. '.number_format($item->total_price);
                })
                ->make();
        }

        return view('transaction.index', $this->data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        DB::beginTransaction();
        $data = Transaction::create([
            'user_id' => Auth::user()->id,
            'status' => 'WAITING',
            'code' => Str::random(3).'/'.Carbon::now()->format('Y-m-d')
        ]);
        if (!$data) {
            DB::rollback();
            return response()->json([
                'status'    => false,
                'message'   => $data
            ], 400);
        }

        $harga = 0;

        if ($request->product_id) {
            foreach ($request->product_id as $key => $value) {
                $product = Product::find($value);

                $harga += $product->harga;

                $titem = TransactionItem::create([
                    'transaction_id' => $data->id,
                    'product_id' => $value
                ]);

                if (!$titem) {
                    DB::rollback();
                    return response()->json([
                        'status'    => false,
                        'message'   => $titem
                    ], 400);
                }

                $cart = Cart::where('product_id', $value)->where('user_id', Auth::user()->id)->first();
                $cart->delete();

            }
        }

        $data->total_price = $harga;
        $data->save();

        DB::commit();
        return response()->json([
            'status'    => true,
            'results'   => route('transaction.index')
        ], 200);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $this->data['data'] = Transaction::getEdit($id);

        return view('transaction.show', $this->data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $this->data['data'] = Transaction::getEdit($id);

        return view('transaction.edit', $this->data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        DB::beginTransaction();
        $product = Transaction::find($id);
        $product->update($request->all());

        if (!$product) {
            DB::rollBack();
            return response()->json([
                'status'    => false,
                'message'   => $product
            ], 400);
        }

        DB::commit();
        return response()->json([
            'status'    => true,
            'results'   => route('transaction.index')
        ], 200);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

}

resources/views/transaction/create.blade.php
@extends('layouts.app')

@section('stylesheets')
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css" rel="stylesheet" />
<link href="{{asset('component/bootstrap-fileinput/css/fileinput.min.css')}}" rel="stylesheet">
<link href="{{asset('component/bootstrap-fileinput/themes/explorer-fas/theme.min.css')}}" rel="stylesheet">
<style>
    .select2-container--default{
        width: inherit !important;
    }
    .select2-container--default .select2-selection--single {
        background-color: #F3F7FF !important;
        height: 34px !important;
    }
    .select2-container--default .select2-selection--single .select2-selection__placeholder{
        color: #c4c4c4;
    }
    .select2-container{
        width: 100% !important;
    }
    .select2-selection{
        height: 2.7em !important;
        padding-top: 0.3em;
    }
</style>
@endsection

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Tambah {{ $title }}</div>

                <div class="card-body">

                    <form id="form" action="{{ route('productcategory.store') }}" method="POST">
                        @csrf
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label>Nama Kategori <b class="text-danger">*</b></label>
                                <input type="text" name="name" class="form-control" placeholder="Nama Kategori">
                            </div>
                        </div>
                        <div class="float-right">
                            <button type="submit" class="btn btn-success">Simpan</button>
                        </div>
                    </form>
                </div>
                <div class="overlay d-none">
                    <i class="fa fa-2x fa-sync-alt fa-spin"></i>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

@push('scripts')
<script src="{{asset('component/validate/jquery.validate.min.js')}}"></script>
<script src="https://cdn.ckeditor.com/ckeditor5/31.0.0/classic/ckeditor.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"></script>
<script src="{{asset('component/bootstrap-fileinput/js/fileinput.min.js')}}"></script>
<script src="{{asset('component/bootstrap-fileinput/themes/explorer-fas/theme.min.js')}}"></script>
    <script>

        $(document).ready(function(){

            $("#form").validate({
                errorElement: 'div',
                errorClass: 'invalid-feedback',
                focusInvalid: false,
                highlight: function (e) {
                    $(e).closest('.form-group').removeClass('has-success').addClass('was-validated has-error');
                },

                success: function (e) {
                    $(e).closest('.form-group').removeClass('has-error').addClass('has-success');
                    $(e).remove();
                },
                errorPlacement: function (error, element) {
                    if(element.is(':file')) {
                    error.insertAfter(element.parent().parent().parent());
                    }else
                    if(element.parent('.input-group').length) {
                    error.insertAfter(element.parent());
                    }
                    else
                    if (element.attr('type') == 'checkbox') {
                        error.insertAfter(element.parent());
                    }
                    else{
                        error.insertAfter(element);
                    }
                    },
                    submitHandler: function() {
                    $.ajax({
                        url:$('#form').attr('action'),
                        method:'post',
                        data: new FormData($('#form')[0]),
                        processData: false,
                        contentType: false,
                        dataType: 'json',
                        beforeSend:function(){
                          $('.overlay').removeClass('d-none');
                        }
                    }).done(function(response){
                        $('.overlay').addClass('d-none');
                        if(response.status){
                            document.location = response.results;
                        }
                        else{
                        $.gritter.add({
                            title: 'Warning!',
                            text: response.message,
                            class_name: 'gritter-warning',
                            time: 1000,
                        });
                        }
                        return;
                    }).fail(function(response){
                        $('.overlay').addClass('d-none');
                        var response = response.responseJSON;
                        $.gritter.add({
                            title: 'Error!',
                            text: response.message,
                            class_name: 'gritter-error',
                            time: 1000,
                        });
                    })
                }
            });


        });
    </script>
@endpush

resources/views/transaction/edit.blade.php
@extends('layouts.app')

@section('stylesheets')
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css" rel="stylesheet" />
<link href="{{asset('component/bootstrap-fileinput/css/fileinput.min.css')}}" rel="stylesheet">
<link href="{{asset('component/bootstrap-fileinput/themes/explorer-fas/theme.min.css')}}" rel="stylesheet">
<style>
    .select2-container--default{
        width: inherit !important;
    }
    .select2-container--default .select2-selection--single {
        background-color: #F3F7FF !important;
        height: 34px !important;
    }
    .select2-container--default .select2-selection--single .select2-selection__placeholder{
        color: #c4c4c4;
    }
    .select2-container{
        width: 100% !important;
    }
    .select2-selection{
        height: 2.7em !important;
        padding-top: 0.3em;
    }
</style>
@endsection

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Edit {{ $title }}</div>

                <div class="card-body">

                    <form id="form" action="{{ route('transaction.update', $data[0]->id) }}" method="POST">
                        @csrf
                        @method('put')
                        <input type="hidden" name="id" class="form-control" value="{{ $data[0]->id }}">
                        <div class="col-sm-12">
                            <div class="row">
                                <p class="col-md-2"> Pelanggan </p>
                                <p class="col-md-1"> : </p>
                                <p class="col-md-6">{{ $data[0]->name }}</p>
                            </div>
                        </div>
                        <div class="col-sm-12">
                            <div class="row">
                                <p class="col-md-2"> Kode transaksi </p>
                                <p class="col-md-1"> : </p>
                                <p class="col-md-6">{{ $data[0]->code }}</p>
                            </div>
                        </div>
                        <div class="col-sm-12">
                            <div class="row">
                                <p class="col-md-2"> Telp </p>
                                <p class="col-md-1"> : </p>
                                <p class="col-md-6">{{ $data[0]->telp ?? '-' }}</p>
                            </div>
                        </div>
                        <div class="col-sm-12">
                            <div class="row">
                                <p class="col-md-2"> Alamat </p>
                                <p class="col-md-1"> : </p>
                                <p class="col-md-6">{{ $data[0]->alamat ?? '-' }}</p>
                            </div>
                        </div>
                        <div class="col-sm-12">
                            <div class="row">
                                <p class="col-md-2"> Status </p>
                                <p class="col-md-1">: </p>
                                <p class="col-md-6">{{ $data[0]->status }}</p>
                            </div>
                        </div>
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Produk</th>
                                    <th>Harga</th>
                                    <th>Qty</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($data as $item)
                                    <tr>
                                        <td>{{ $item->nama }}</td>
                                        <td>Rp. {{ number_format($item->harga) }}</td>
                                        <td>{{ $item->qty }}</td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                        <div class="col-sm-12 ">
                            <div class="row">
                                <p class="col-md-2"> Total </p>
                                <p class="col-md-1">: </p>
                                <p class="col-md-6">Rp. {{ number_format($data[0]->total_price) }}</p>
                            </div>
                        </div>
                        <div class="float-right">
                            @if ($data[0]->status == 'PROSES')
                                <a href="#" data-status="FINISH" class="btn btn-success submit">Finish</a>
                            @elseif($data[0]->status == 'WAITING')
                                <a href="#" data-status="PROSES" class="btn btn-warning submit">Proses</a>
                                <a href="#" data-status="REJECT" class="btn btn-danger submit">Reject</a>
                            @endif
                        </div>
                    </form>

                </div>
                <div class="overlay d-none">
                    <i class="fa fa-2x fa-sync-alt fa-spin"></i>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@push('scripts')
<script src="{{asset('component/validate/jquery.validate.min.js')}}"></script>
<script src="https://cdn.ckeditor.com/ckeditor5/31.0.0/classic/ckeditor.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"></script>
<script src="{{asset('component/bootstrap-fileinput/js/fileinput.min.js')}}"></script>
<script src="{{asset('component/bootstrap-fileinput/themes/explorer-fas/theme.min.js')}}"></script>
    <script>

        $(document).ready(function(){

            $(document).on('click','.submit',function(){
                var data = new FormData($('#form')[0]);
                var status = $(this).data('status');
                data.append('status', status);

                $.ajax({
                    url:$('#form').attr('action'),
                    method:'post',
                    data: data,
                    processData: false,
                    contentType: false,
                    dataType: 'json',
                    beforeSend:function(){
                    $('.overlay').removeClass('d-none');
                    }
                }).done(function(response){
                    $('.overlay').addClass('d-none');
                    if(response.status){
                    document.location = response.results;
                    }
                    else{
                    $.gritter.add({
                        title: 'Warning!',
                        text: response.message,
                        class_name: 'gritter-warning',
                        time: 1000,
                    });
                    }
                    return;
                }).fail(function(response){
                    $('.overlay').addClass('d-none');
                    var response = response.responseJSON;
                    $.gritter.add({
                    title: 'Error!',
                    text: response.message,
                    class_name: 'gritter-error',
                    time: 1000,
                    });
                })
            })

        });

    </script>
@endpush

resources/views/transaction/index.blade.php
@extends('layouts.app')

@section('stylesheets')
<link href="{{asset('component/dataTables/css/datatables.min.css')}}" rel="stylesheet">
@endsection

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    {{ $title }}
                    {{-- <a href="{{ route('product.create') }}" class="btn btn-success btn-sm float-right">+ Tambah {{ $title }}</a> --}}
                </div>

                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered" id="table-product">
                            <thead>
                                <tr>
                                    <th>No</th>
                                    <th>Kode Transaksi</th>
                                    <th>Nama Pelanggan</th>
                                    <th>status</th>
                                    <th>aksi</th>
                                </tr>
                            </thead>
                            <tbody>

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@push('scripts')
    <script src="{{asset('component/dataTables/js/datatables.min.js')}}"></script>
    <script>
        $(document).ready(function(){

            dataTable = $('#table-product').DataTable({
            stateSave:true,
            processing:true,
            serverSide:true,
            info:false,
            lengthChange:true,
            responsive:true,
            ajax: {
                url: '{!! url()->current() !!}',
                type: "GET",
                data: function(data){
                },
            },
            columnDefs: [
            {
                render: function(data, type, row) {
					switch (data) {
                        case 'WAITING':
                            return `<span class="badge badge-warning">Waiting</span>`;
                            break;
                        case 'PROSES':
                            return `<span class="badge badge-primary">Proses</span>`;
                            break;
                        case 'REJECT':
                            return `<span class="badge badge-danger">Reject</span>`;
                            break;
                        case 'FINISH':
                            return `<span class="badge badge-success">Finish</span>`;
                            break;

                        default:
                            break;
                    }
				}, targets:[3]
            },
        ],
            columns: [
                { data: "DT_RowIndex" },
                { data: "code" },
                { data: "customer" },
                { data: "status", class:'text-center' },
                { data: "action", orderable: false, searchable: false, class: 'text-center' },
            ]
        });

        $(document).on('click','.delete',function(){
            var url = $(this).data('url');
            bootbox.confirm({
                buttons: {
                    confirm: {
                        label: '<i class="fa fa-check"></i>',
                        className: 'btn btn-danger'
                    },
                    cancel: {
                        label: '<i class="fa fa-undo"></i>',
                        className: 'btn btn-secondary'
                    },
                },
                title:'Hapus Produk Kategori?',
                message:'Data yang dihapus tdak bisa dikembalikan',
                callback: function(result) {
                        if(result) {
                            var data = {
                                _token: "{{ csrf_token() }}"
                            };
                            $.ajax({
                                url: url,
                                dataType: 'json',
                                data:data,
                                type:'DELETE',
                                beforeSend:function(){
                                    $('.overlay').removeClass('hidden');
                                }
                            }).done(function(response){
                                if(response.status){
                                    $('.overlay').addClass('hidden');
                                    $.gritter.add({
                                        title: 'Success!',
                                        text: response.message,
                                        class_name: 'gritter-success',
                                        time: 1000,
                                    });
                                    dataTable.ajax.reload( null, false );
                                }
                                else{
                                    $.gritter.add({
                                        title: 'Warning!',
                                        text: response.message,
                                        class_name: 'gritter-warning',
                                        time: 1000,
                                    });
                                }
                            }).fail(function(response){
                                var response = response.responseJSON;
                                $('.overlay').addClass('hidden');
                                $.gritter.add({
                                    title: 'Error!',
                                    text: response.message,
                                    class_name: 'gritter-error',
                                    time: 1000,
                                });
                            })
                        }
                }
            });
        })
    });

    </script>
@endpush