routes/web.php
<?php

use App\Http\Controllers\CartController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\ProductCategoryController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\TransactionController;
use App\Http\Controllers\WelcomeController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [WelcomeController::class, 'index']);
Route::post('/chart', [WelcomeController::class, 'chart']);

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::middleware('auth')->group( function () {
    Route::get('product/categoryselect', [ProductController::class, 'categoryselect']);
    Route::resource('product', ProductController::class);

    Route::resource('productcategory', ProductCategoryController::class);
    Route::resource('customer', CustomerController::class);

    Route::resource('cart', CartController::class);
    Route::resource('transaction', TransactionController::class);
});

app/Models/Customer.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Customer extends Model
{
    use HasFactory;

    protected $guarded = [];
}

app/Http/Controllers/CustomerController.php
<?php

namespace App\Http\Controllers;

use App\Models\Customer;
use Illuminate\Http\Request;
use Yajra\DataTables\Facades\DataTables;

class CustomerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public $data = [
        'title' => 'Customer',
    ];

    public function index()
    {
        if (request()->ajax()) {

            $query = Customer::get();


            return  DataTables::of($query)
                ->addIndexColumn()
                ->addColumn('action', function($item){
                    return '
                        <a class="btn btn-primary btn-sm" href="'.route('productcategory.edit', $item->id).'">
                            Edit
                        </a>
                        <a class="btn btn-warning btn-sm" href="'.route('productcategory.show', $item->id).'">
                            Detail
                        </a>
                        <a class="btn btn-danger btn-sm delete" href="#" data-url="'.route('productcategory.destroy', $item->id).'">
                            Delete
                        </a>
                    ';
                })
                ->make();
        }

        return view('customer.index', $this->data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/customer/create.blade.php
@extends('layouts.app')

@section('stylesheets')
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css" rel="stylesheet" />
<link href="{{asset('component/bootstrap-fileinput/css/fileinput.min.css')}}" rel="stylesheet">
<link href="{{asset('component/bootstrap-fileinput/themes/explorer-fas/theme.min.css')}}" rel="stylesheet">
<style>
    .select2-container--default{
        width: inherit !important;
    }
    .select2-container--default .select2-selection--single {
        background-color: #F3F7FF !important;
        height: 34px !important;
    }
    .select2-container--default .select2-selection--single .select2-selection__placeholder{
        color: #c4c4c4;
    }
    .select2-container{
        width: 100% !important;
    }
    .select2-selection{
        height: 2.7em !important;
        padding-top: 0.3em;
    }
</style>
@endsection

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Tambah {{ $title }}</div>

                <div class="card-body">

                    <form id="form" action="{{ route('product.store') }}" method="POST">
                        @csrf
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label>Nama Produk <b class="text-danger">*</b></label>
                                <input type="text" name="nama" class="form-control" placeholder="Nama Produk">
                            </div>
                        </div>
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label>Deskripsi <b class="text-danger">*</b></label>
                                <textarea style="height: 120px;" class="form-control" id="deskripsi" name="deskripsi"
                                    placeholder="Deskripsi"></textarea>
                            </div>
                        </div>
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label>Harga Produk <b class="text-danger">*</b></label>
                                <input type="number" name="harga" class="form-control" placeholder="Harga Produk">
                            </div>
                        </div>
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label>Produk Kategori <b class="text-danger">*</b></label>
                                <select class="form-control" id="category_id" name="category_id">
                                    <option value="">asd</option>
                                </select>
                            </div>
                        </div>
                        <div class="col-sm-12">
                            <div class="form-group row">
                                <label for="image" class="col-sm-2 col-form-label">Gambar</label>
                                <div class="col-sm-12">
                                    <input type="file" class="form-control" name="image" id="image" accept="image/*" />
                                </div>
                            </div>
                        </div>
                        <div class="float-right">
                            <button type="submit" class="btn btn-success">Simpan</button>
                        </div>
                    </form>
                </div>
                <div class="overlay d-none">
                    <i class="fa fa-2x fa-sync-alt fa-spin"></i>
                </div>
            </div>
        </div>
    </div>
</div>
                
@endsection

@push('scripts')
<script src="{{asset('component/validate/jquery.validate.min.js')}}"></script>
<script src="https://cdn.ckeditor.com/ckeditor5/31.0.0/classic/ckeditor.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"></script>
<script src="{{asset('component/bootstrap-fileinput/js/fileinput.min.js')}}"></script>
<script src="{{asset('component/bootstrap-fileinput/themes/explorer-fas/theme.min.js')}}"></script>
    <script>

        $(document).ready(function(){
            // ckeditor
            ClassicEditor
            .create( document.querySelector( '#deskripsi' ) )
            .catch( error => {
                console.error( error );
            } );

            // select cateogry
            $( "#category_id" ).select2({
                ajax: {
                    url: "{{url('product/categoryselect')}}",
                    type:'GET',
                    dataType: 'json',
                    data: function (params) {
                        var query = {
                            name: params.term,
                            page: params.page || 1,
                            limit: 30
                        }
                    return query;
                    },
                    processResults: function (data, params) {
                        params.page = params.page || 1;

                        return {
                            results: data.rows,
                            pagination: {
                                more: (params.page * 30) < data.total
                            }
                        };
                    },
                    cache: true
                },
                placeholder: 'Produk Kategori',
                templateResult: formatRepo,
                templateSelection: formatRepoSelection
            });

            $("#image").fileinput({
                browseClass: "btn btn-primary",
                showRemove: false,
                showUpload: true,
                allowedFileExtensions: ["png", "jpg", "jpeg"],
                dropZoneEnabled: false,
                initialPreviewFileType: 'image',
                theme: 'explorer-fas'
            });

            $("#form").validate({
                errorElement: 'div',
                errorClass: 'invalid-feedback',
                focusInvalid: false,
                highlight: function (e) {
                    $(e).closest('.form-group').removeClass('has-success').addClass('was-validated has-error');
                },

                success: function (e) {
                    $(e).closest('.form-group').removeClass('has-error').addClass('has-success');
                    $(e).remove();
                },
                errorPlacement: function (error, element) {
                    if(element.is(':file')) {
                    error.insertAfter(element.parent().parent().parent());
                    }else
                    if(element.parent('.input-group').length) {
                    error.insertAfter(element.parent());
                    }
                    else
                    if (element.attr('type') == 'checkbox') {
                        error.insertAfter(element.parent());
                    }
                    else{
                        error.insertAfter(element);
                    }
                    },
                    submitHandler: function() {
                    $.ajax({
                        url:$('#form').attr('action'),
                        method:'post',
                        data: new FormData($('#form')[0]),
                        processData: false,
                        contentType: false,
                        dataType: 'json',
                        beforeSend:function(){
                          $('.overlay').removeClass('d-none');
                        }
                    }).done(function(response){
                        $('.overlay').addClass('d-none');
                        if(response.status){
                            document.location = response.results;
                        }
                        else{
                        $.gritter.add({
                            title: 'Warning!',
                            text: response.message,
                            class_name: 'gritter-warning',
                            time: 1000,
                        });
                        }
                        return;
                    }).fail(function(response){
                        $('.overlay').addClass('d-none');
                        var response = response.responseJSON;
                        $.gritter.add({
                            title: 'Error!',
                            text: response.message,
                            class_name: 'gritter-error',
                            time: 1000,
                        });
                    })
                }
            });


        });
        function formatRepo (data) {
            if (data.loading) {
                return data.text;
            }

            var markup = data.name;

            return markup;
        }

        function formatRepoSelection (repo) {
            return repo.name || repo.text;
        }

    </script>
@endpush

resources/views/customer/edit.blade.php
@extends('layouts.app')

@section('stylesheets')
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css" rel="stylesheet" />
<link href="{{asset('component/bootstrap-fileinput/css/fileinput.min.css')}}" rel="stylesheet">
<link href="{{asset('component/bootstrap-fileinput/themes/explorer-fas/theme.min.css')}}" rel="stylesheet">
<style>
    .select2-container--default{
        width: inherit !important;
    }
    .select2-container--default .select2-selection--single {
        background-color: #F3F7FF !important;
        height: 34px !important;
    }
    .select2-container--default .select2-selection--single .select2-selection__placeholder{
        color: #c4c4c4;
    }
    .select2-container{
        width: 100% !important;
    }
    .select2-selection{
        height: 2.7em !important;
        padding-top: 0.3em;
    }
</style>
@endsection

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Edit {{ $title }}</div>

                <div class="card-body">

                    <form id="form" action="{{ route('product.update', $data->id) }}" method="POST">
                        @csrf
                        @method('put')
                        <input type="hidden" name="id" class="form-control" value="{{ $data->id }}">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label>Nama Produk <b class="text-danger">*</b></label>
                                <input type="text" name="nama" class="form-control" value="{{ $data->nama }}" placeholder="Nama Produk">
                            </div>
                        </div>
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label>Deskripsi <b class="text-danger">*</b></label>
                                <textarea style="height: 120px;" class="form-control" id="deskripsi" name="deskripsi"
                                    placeholder="Deskripsi">{!! $data->deskripsi !!}</textarea>
                            </div>
                        </div>
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label>Harga Produk <b class="text-danger">*</b></label>
                                <input type="number" name="harga" class="form-control" value="{{ $data->harga }}" placeholder="Harga Produk">
                            </div>
                        </div>
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label>Produk Kategori <b class="text-danger">*</b></label>
                                <select class="form-control" id="category_id" name="category_id">
                                </select>
                            </div>
                        </div>
                        <div class="col-sm-12">
                            <div class="form-group row">
                                <label for="image" class="col-sm-2 col-form-label">Gambar</label>
                                <div class="col-sm-12">
                                    <input type="file" class="form-control" name="image" id="image" accept="image/*" />
                                </div>
                            </div>
                        </div>
                        <div class="float-right">
                            <button type="submit" class="btn btn-success">Simpan</button>
                        </div>
                    </form>

                </div>
                <div class="overlay d-none">
                    <i class="fa fa-2x fa-sync-alt fa-spin"></i>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@push('scripts')
<script src="{{asset('component/validate/jquery.validate.min.js')}}"></script>
<script src="https://cdn.ckeditor.com/ckeditor5/31.0.0/classic/ckeditor.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"></script>
<script src="{{asset('component/bootstrap-fileinput/js/fileinput.min.js')}}"></script>
<script src="{{asset('component/bootstrap-fileinput/themes/explorer-fas/theme.min.js')}}"></script>
    <script>

        $(document).ready(function(){
            // ckeditor
            ClassicEditor
            .create( document.querySelector( '#deskripsi' ) )
            .catch( error => {
                console.error( error );
            } );

            // select cateogry
            $( "#category_id" ).select2({
                ajax: {
                    url: "{{url('product/categoryselect')}}",
                    type:'GET',
                    dataType: 'json',
                    data: function (params) {
                        var query = {
                            name: params.term,
                            page: params.page || 1,
                            limit: 30
                        }
                    return query;
                    },
                    processResults: function (data, params) {
                        params.page = params.page || 1;

                        return {
                            results: data.rows,
                            pagination: {
                                more: (params.page * 30) < data.total
                            }
                        };
                    },
                    cache: true
                },
                placeholder: 'Produk Kategori',
                templateResult: formatRepo,
                templateSelection: formatRepoSelection
            });

           $("#category_id").select2('trigger', 'select', {
                data: {
                    id: {{$data -> product_category_id}},
                    text: '{{$data->category->name}}'
                }
            });

            $("#image").fileinput({
                browseClass: "btn btn-primary",
                showRemove: false,
                showUpload: true,
                allowedFileExtensions: ["png", "jpg", "jpeg"],
                dropZoneEnabled: false,
                initialPreviewFileType: 'image',
                theme: 'explorer-fas',
                initialPreview: '<img src="{{asset($data->image)}}" class="kv-preview-data file-preview-image">',
                initialPreviewAsData: false,
                initialPreviewFileType: 'image',
                initialPreviewConfig: [
                    {
                        caption: "{{$data->image}}", 
                        downloadUrl: "{{asset($data->image)}}",
                        size:"{{ @File::size(public_path($data->image))}}",
                        url: false}
                ],
            });

            $("#form").validate({
                errorElement: 'div',
                errorClass: 'invalid-feedback',
                focusInvalid: false,
                highlight: function (e) {
                    $(e).closest('.form-group').removeClass('has-success').addClass('was-validated has-error');
                },

                success: function (e) {
                    $(e).closest('.form-group').removeClass('has-error').addClass('has-success');
                    $(e).remove();
                },
                errorPlacement: function (error, element) {
                    if(element.is(':file')) {
                    error.insertAfter(element.parent().parent().parent());
                    }else
                    if(element.parent('.input-group').length) {
                    error.insertAfter(element.parent());
                    }
                    else
                    if (element.attr('type') == 'checkbox') {
                        error.insertAfter(element.parent());
                    }
                    else{
                        error.insertAfter(element);
                    }
                    },
                    submitHandler: function() {
                    $.ajax({
                        url:$('#form').attr('action'),
                        method:'post',
                        data: new FormData($('#form')[0]),
                        processData: false,
                        contentType: false,
                        dataType: 'json',
                        beforeSend:function(){
                        $('.overlay').removeClass('d-none');
                        }
                    }).done(function(response){
                        $('.overlay').addClass('d-none');
                        if(response.status){
                        document.location = response.results;
                        }
                        else{
                        $.gritter.add({
                            title: 'Warning!',
                            text: response.message,
                            class_name: 'gritter-warning',
                            time: 1000,
                        });
                        }
                        return;
                    }).fail(function(response){
                        $('.overlay').addClass('d-none');
                        var response = response.responseJSON;
                        $.gritter.add({
                        title: 'Error!',
                        text: response.message,
                        class_name: 'gritter-error',
                        time: 1000,
                        });
                    })
                }
            });


        });
        function formatRepo (data) {
            if (data.loading) {
                return data.text;
            }

            var markup = data.name;

            return markup;
        }

        function formatRepoSelection (repo) {
            return repo.name || repo.text;
        }

    </script>
@endpush

resources/views/customer/index.blade.php
@extends('layouts.app')

@section('stylesheets')
<link href="{{asset('component/dataTables/css/datatables.min.css')}}" rel="stylesheet">
@endsection

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    {{ $title }}
                    {{-- <a href="{{ route('product.create') }}" class="btn btn-success btn-sm float-right">+ Tambah {{ $title }}</a> --}}
                </div>

                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered" id="table-product">
                            <thead>
                                <tr>
                                    <th>No</th>
                                    <th>Nama</th>
                                    <th>Telp</th>
                                    <th>Alamat</th>
                                </tr>
                            </thead>
                            <tbody>

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@push('scripts')
    <script src="{{asset('component/dataTables/js/datatables.min.js')}}"></script>
    <script>
        $(document).ready(function(){

            dataTable = $('#table-product').DataTable({
            stateSave:true,
            processing:true,
            serverSide:true,
            info:false,
            lengthChange:true,
            responsive:true,
            ajax: {
                url: '{!! url()->current() !!}',
                type: "GET",
                data: function(data){
                },
            },
            columns: [
                { data: "DT_RowIndex" },
                { data: "name" },
                { data: "telp" },
                { data: "alamat" },
            ]
        });

        $(document).on('click','.delete',function(){
            var url = $(this).data('url');
            bootbox.confirm({
                buttons: {
                    confirm: {
                        label: '<i class="fa fa-check"></i>',
                        className: 'btn btn-danger'
                    },
                    cancel: {
                        label: '<i class="fa fa-undo"></i>',
                        className: 'btn btn-secondary'
                    },
                },
                title:'Hapus Product?',
                message:'Data yang dihapus tdak bisa dikembalikan',
                callback: function(result) {
                        if(result) {
                            var data = {
                                _token: "{{ csrf_token() }}"
                            };
                            $.ajax({
                                url: url,
                                dataType: 'json',
                                data:data,
                                type:'DELETE',
                                beforeSend:function(){
                                    $('.overlay').removeClass('hidden');
                                }
                            }).done(function(response){
                                if(response.status){
                                    $('.overlay').addClass('hidden');
                                    $.gritter.add({
                                        title: 'Success!',
                                        text: response.message,
                                        class_name: 'gritter-success',
                                        time: 1000,
                                    });
                                    dataTable.ajax.reload( null, false );
                                }
                                else{
                                    $.gritter.add({
                                        title: 'Warning!',
                                        text: response.message,
                                        class_name: 'gritter-warning',
                                        time: 1000,
                                    });
                                }
                            }).fail(function(response){
                                var response = response.responseJSON;
                                $('.overlay').addClass('hidden');
                                $.gritter.add({
                                    title: 'Error!',
                                    text: response.message,
                                    class_name: 'gritter-error',
                                    time: 1000,
                                });
                            })
                        }
                }
            });
        })
    });

    </script>
@endpush